package buildcraft.datagen;

import static buildcraft.datagen.BCRecipeProvider.cd;
import static buildcraft.datagen.BCRecipeProvider.i;
import static buildcraft.datagen.BCRecipeProvider.keys;
import static buildcraft.datagen.BCRecipeProvider.shaped;
import static buildcraft.datagen.BCRecipeProvider.shapeless;

import buildcraft.datagen.BCRecipeProvider.Def;
import java.util.List;

final class BCRecipeDefs {
   static final List<Def> ALL = List.of(
      shaped("buildcraftbuilders:architect", "misc", null, null,
         List.of("bmb", "ycy", "dsd"),
         keys('b', i("#c:dyes/black"), 'm', i("buildcraftcore:marker_volume"), 'y', i("#c:dyes/yellow"), 'c', i("minecraft:crafting_table"), 'd', i("buildcraftcore:gear_diamond"), 's', i("buildcraftbuilders:blueprint_clean")),
         "buildcraftbuilders:architect", 1, null),
      shaped("buildcraftbuilders:blueprint_clean", "misc", null, null,
         List.of("ppp", "pbp", "ppp"),
         keys('p', i("minecraft:paper"), 'b', i("#c:gems/lapis")),
         "buildcraftbuilders:blueprint_clean", 2, null),
      shaped("buildcraftbuilders:builder", "misc", null, null,
         List.of("pmf", "gcg", "tbl"),
         keys('p', i("buildcraftfactory:pump"), 'm', i("buildcraftcore:marker_volume"), 'f', i("buildcraftfactory:flood_gate"), 'g', i("buildcraftcore:gear_diamond"), 'c', i("buildcraftfactory:chute"), 't', i("buildcraftfactory:tank"), 'b', i("buildcraftbuilders:blueprint_clean"), 'l', i("buildcraftbuilders:filler")),
         "buildcraftbuilders:builder", 1, null),
      shaped("buildcraftbuilders:filler", "misc", null, null,
         List.of("bmb", "ywy", "gcg"),
         keys('b', i("#c:dyes/black"), 'm', i("buildcraftcore:marker_volume"), 'y', i("#c:dyes/yellow"), 'w', i("buildcraftfactory:mining_well"), 'g', i("buildcraftcore:gear_gold"), 'c', i("minecraft:chest")),
         "buildcraftbuilders:filler", 1, null),
      shaped("buildcraftbuilders:library", "misc", null, null,
         List.of("igi", "bBb", "iri"),
         keys('i', i("#c:ingots/iron"), 'g', i("buildcraftcore:gear_iron"), 'b', i("minecraft:bookshelf"), 'B', i("buildcraftbuilders:blueprint_clean"), 'r', i("minecraft:redstone")),
         "buildcraftbuilders:library", 1, null),
      shaped("buildcraftbuilders:quarry", "misc", null, null,
         List.of("iri", "gig", "dpd"),
         keys('i', i("buildcraftcore:gear_iron"), 'g', i("buildcraftcore:gear_gold"), 'd', i("buildcraftcore:gear_diamond"), 'r', i("#c:dusts/redstone"), 'p', i("minecraft:diamond_pickaxe")),
         "buildcraftbuilders:quarry", 1, null),
      shaped("buildcraftbuilders:replacer", "misc", null, null,
         List.of("gqg", "sAs", "gqg"),
         keys('g', i("buildcraftcore:gear_gold"), 'q', i("minecraft:quartz_block"), 's', i("buildcraftbuilders:schematic_single_clean"), 'A', i("buildcraftbuilders:architect")),
         "buildcraftbuilders:replacer", 1, null),
      shapeless("buildcraftbuilders:schematic_single_clean", "misc", null, null,
         List.of(i("minecraft:paper"), i("minecraft:paper"), i("#c:gems/lapis")),
         "buildcraftbuilders:schematic_single_clean", 4, null),
      shaped("buildcraftbuilders:template_clean", "misc", null, null,
         List.of("ppp", "pbp", "ppp"),
         keys('p', i("minecraft:paper"), 'b', i("#c:dyes/black")),
         "buildcraftbuilders:template_clean", 4, null),
      shaped("buildcraftcore:decorated_laser", "building", null, null,
         List.of("sss", "scs", "sss"),
         keys('s', i("minecraft:obsidian"), 'c', i("minecraft:redstone_block")),
         "buildcraftcore:decorated_laser", 16, null),
      shaped("buildcraftcore:diamond_shard", "misc", null, null,
         List.of("D"),
         keys('D', i("#c:gems/diamond")),
         "buildcraftcore:diamond_shard", 4, null),
      shaped("buildcraftcore:engine_redstone", "misc", null, null,
         List.of("www", " g ", "GpG"),
         keys('w', i("#minecraft:planks"), 'g', i("#c:glass_blocks/colorless"), 'G', i("buildcraftcore:gear_wood"), 'p', i("minecraft:piston")),
         "buildcraftcore:engine_redstone", 1, null),
      shaped("buildcraftcore:gear_diamond", "misc", "buildcraft_gears", null,
         List.of(" d ", "dGd", " d "),
         keys('d', i("#c:gems/diamond"), 'G', i("#c:gears/gold")),
         "buildcraftcore:gear_diamond", 1, null),
      shaped("buildcraftcore:gear_gold", "misc", "buildcraft_gears", null,
         List.of(" g ", "gGg", " g "),
         keys('g', i("#c:ingots/gold"), 'G', i("#c:gears/iron")),
         "buildcraftcore:gear_gold", 1, null),
      shaped("buildcraftcore:gear_iron", "misc", "buildcraft_gears", null,
         List.of(" i ", "iGi", " i "),
         keys('i', i("#c:ingots/iron"), 'G', i("#c:gears/stone")),
         "buildcraftcore:gear_iron", 1, null),
      shaped("buildcraftcore:gear_stone", "misc", "buildcraft_gears", null,
         List.of(" c ", "cGc", " c "),
         keys('c', i("#minecraft:stone_crafting_materials"), 'G', i("#c:gears/wooden")),
         "buildcraftcore:gear_stone", 1, null),
      shaped("buildcraftcore:gear_wood", "misc", "buildcraft_gears", null,
         List.of(" s ", "s s", " s "),
         keys('s', i("#c:rods/wooden")),
         "buildcraftcore:gear_wood", 1, null),
      shaped("buildcraftcore:list", "misc", null, null,
         List.of("pRp", "pGp", "ppp"),
         keys('p', i("minecraft:paper"), 'R', i("#c:dusts/redstone"), 'G', i("minecraft:green_dye")),
         "buildcraftcore:list", 1, null),
      shaped("buildcraftcore:map_location", "misc", null, null,
         List.of("ppp", "pYp", "ppp"),
         keys('p', i("minecraft:paper"), 'Y', i("minecraft:yellow_dye")),
         "buildcraftcore:map_location", 1, null),
      shaped("buildcraftcore:marker_connector", "misc", null, null,
         List.of("r", "g", "w"),
         keys('r', i("minecraft:redstone_torch"), 'g', i("buildcraftcore:gear_wood"), 'w', i("buildcraftcore:wrench")),
         "buildcraftcore:marker_connector", 1, null),
      shaped("buildcraftcore:marker_path", "misc", null, null,
         List.of("g", "t"),
         keys('g', i("minecraft:green_dye"), 't', i("minecraft:redstone_torch")),
         "buildcraftcore:marker_path", 1, null),
      shaped("buildcraftcore:marker_volume", "misc", null, null,
         List.of("l", "t"),
         keys('l', i("minecraft:lapis_lazuli"), 't', i("minecraft:redstone_torch")),
         "buildcraftcore:marker_volume", 1, null),
      shaped("buildcraftcore:paintbrush", "misc", null, null,
         List.of(" iw", " gi", "s  "),
         keys('i', i("#c:strings"), 'g', i("buildcraftcore:gear_wood"), 's', i("#c:rods/wooden"), 'w', i("#minecraft:wool")),
         "buildcraftcore:paintbrush", 1, null),
      shapeless("buildcraftcore:paintbrush_black", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/black")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"black\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[16.0]}}"),
      shapeless("buildcraftcore:paintbrush_blue", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/blue")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"blue\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[12.0]}}"),
      shapeless("buildcraftcore:paintbrush_brown", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/brown")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"brown\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[13.0]}}"),
      shapeless("buildcraftcore:paintbrush_cyan", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/cyan")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"cyan\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[10.0]}}"),
      shapeless("buildcraftcore:paintbrush_gray", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/gray")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"gray\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[8.0]}}"),
      shapeless("buildcraftcore:paintbrush_green", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/green")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"green\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[14.0]}}"),
      shapeless("buildcraftcore:paintbrush_light_blue", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/light_blue")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"light_blue\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[4.0]}}"),
      shapeless("buildcraftcore:paintbrush_light_gray", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/light_gray")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"light_gray\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[9.0]}}"),
      shapeless("buildcraftcore:paintbrush_lime", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/lime")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"lime\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[6.0]}}"),
      shapeless("buildcraftcore:paintbrush_magenta", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/magenta")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"magenta\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[3.0]}}"),
      shapeless("buildcraftcore:paintbrush_orange", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/orange")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"orange\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[2.0]}}"),
      shapeless("buildcraftcore:paintbrush_pink", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/pink")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"pink\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[7.0]}}"),
      shapeless("buildcraftcore:paintbrush_purple", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/purple")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"purple\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[11.0]}}"),
      shapeless("buildcraftcore:paintbrush_red", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/red")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"red\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[15.0]}}"),
      shapeless("buildcraftcore:paintbrush_white", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/white")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"white\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[1.0]}}"),
      shapeless("buildcraftcore:paintbrush_yellow", "misc", "buildcraft_paintbrush", null,
         List.of(i("buildcraftcore:paintbrush"), i("#c:dyes/yellow")),
         "buildcraftcore:paintbrush", 1, "{\"buildcraftcore:brush_color\":\"yellow\",\"buildcraftcore:brush_uses\":64,\"minecraft:custom_model_data\":{\"floats\":[5.0]}}"),
      shaped("buildcraftcore:wrench", "misc", null, null,
         List.of("I I", " G ", " I "),
         keys('I', i("#c:ingots/iron"), 'G', i("buildcraftcore:gear_stone")),
         "buildcraftcore:wrench", 1, null),
      shaped("buildcraftenergy:engine_iron", "misc", null, null,
         List.of("www", " g ", "GpG"),
         keys('w', i("#c:ingots/iron"), 'g', i("#c:glass_blocks/colorless"), 'G', i("buildcraftcore:gear_iron"), 'p', i("minecraft:piston")),
         "buildcraftenergy:engine_iron", 1, null),
      shaped("buildcraftenergy:engine_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of("www", " g ", "GpG"),
         keys('w', i("minecraft:redstone"), 'g', i("#c:glass_blocks/colorless"), 'G', i("buildcraftcore:gear_iron"), 'p', i("minecraft:piston")),
         "buildcraftenergy:engine_rf", 1, null),
      shaped("buildcraftenergy:engine_stone", "misc", null, null,
         List.of("www", " g ", "GpG"),
         keys('w', i("#c:cobblestones/normal"), 'g', i("#c:glass_blocks/colorless"), 'G', i("buildcraftcore:gear_stone"), 'p', i("minecraft:piston")),
         "buildcraftenergy:engine_stone", 1, null),
      shaped("buildcraftenergy:mj_dynamo", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of("wgw", " p ", "GwG"),
         keys('w', i("minecraft:redstone"), 'g', i("#c:glass_blocks/colorless"), 'p', i("minecraft:piston"), 'G', i("buildcraftcore:gear_iron")),
         "buildcraftenergy:mj_dynamo", 1, null),
      shaped("buildcraftfactory:autoworkbench_item", "misc", null, null,
         List.of("gwg"),
         keys('g', i("buildcraftcore:gear_stone"), 'w', i("minecraft:crafting_table")),
         "buildcraftfactory:autoworkbench_item", 1, null),
      shaped("buildcraftfactory:chute", "misc", null, null,
         List.of("ici", "igi", " i "),
         keys('i', i("#c:ingots/iron"), 'c', i("#c:chests/wooden"), 'g', i("buildcraftcore:gear_stone")),
         "buildcraftfactory:chute", 1, null),
      shaped("buildcraftfactory:distiller", "misc", null, null,
         List.of("rtr", "tgt"),
         keys('r', i("minecraft:redstone_torch"), 't', i("buildcraftfactory:tank"), 'g', i("buildcraftcore:gear_diamond")),
         "buildcraftfactory:distiller", 1, null),
      shaped("buildcraftfactory:flood_gate", "misc", null, null,
         List.of("igi", "btb", "ibi"),
         keys('i', i("#c:ingots/iron"), 'g', i("buildcraftcore:gear_iron"), 'b', i("minecraft:iron_bars"), 't', i("buildcraftfactory:tank")),
         "buildcraftfactory:flood_gate", 1, null),
      shaped("buildcraftfactory:heat_exchange", "misc", null, null,
         List.of("igi", "###", "igi"),
         keys('i', i("#c:ingots/iron"), 'g', i("buildcraftcore:gear_iron"), '#', i("#c:glass_blocks/colorless")),
         "buildcraftfactory:heat_exchange", 1, null),
      shaped("buildcraftfactory:mining_well", "misc", null, null,
         List.of("iri", "igi", "ipi"),
         keys('i', i("#c:ingots/iron"), 'r', i("#c:dusts/redstone"), 'g', i("buildcraftcore:gear_iron"), 'p', i("minecraft:iron_pickaxe")),
         "buildcraftfactory:mining_well", 1, null),
      shaped("buildcraftfactory:pump", "misc", null, null,
         List.of("iri", "igi", "tbt"),
         keys('i', i("#c:ingots/iron"), 'r', i("#c:dusts/redstone"), 'g', i("buildcraftcore:gear_iron"), 't', i("buildcraftfactory:tank"), 'b', i("minecraft:bucket")),
         "buildcraftfactory:pump", 1, null),
      shaped("buildcraftfactory:tank", "misc", null, null,
         List.of("ggg", "g g", "ggg"),
         keys('g', i("#c:glass_blocks/cheap")),
         "buildcraftfactory:tank", 1, null),
      shaped("buildcraftfactory:water_gel_spawn", "misc", null, null,
         List.of(" s ", "srs", " s "),
         keys('s', i("minecraft:sand"), 'r', i("buildcraftenergy:oil_residue_bucket")),
         "buildcraftfactory:water_gel_spawn", 1, null),
      shaped("buildcraftfactory:water_gel_to_bucket", "misc", null, null,
         List.of("g", "b"),
         keys('g', i("buildcraftfactory:gelled_water"), 'b', i("minecraft:bucket")),
         "minecraft:water_bucket", 1, null),
      shapeless("buildcraftlib:guide_book", "misc", "buildcraft", null,
         List.of(i("buildcraftcore:gear_wood"), i("minecraft:paper"), i("minecraft:paper"), i("minecraft:paper")),
         "buildcraftlib:guide", 1, null),
      shaped("buildcraftrobotics:redstone_board", "misc", null, null,
         List.of("PPP", "PRP", "PPP"),
         keys('P', i("minecraft:paper"), 'R', i("minecraft:redstone")),
         "buildcraftrobotics:redstone_board", 8, null),
      shaped("buildcraftrobotics:requester", "misc", null, null,
         List.of("IPI", "GCG", "IRI"),
         keys('I', i("#c:ingots/iron"), 'P', i("minecraft:piston"), 'G', i("buildcraftcore:gear_iron"), 'C', i("minecraft:chest"), 'R', i("minecraft:redstone")),
         "buildcraftrobotics:requester", 1, null),
      shaped("buildcraftrobotics:robot", "misc", null, null,
         List.of("III", "IRI", "D D"),
         keys('I', i("#c:ingots/iron"), 'R', i("buildcraftsilicon:chipset_redstone"), 'D', i("buildcraftsilicon:chipset_diamond")),
         "buildcraftrobotics:robot", 1, null),
      shaped("buildcraftrobotics:robot_station", "misc", null, null,
         List.of("   ", " I ", "ICI"),
         keys('I', i("#c:ingots/iron"), 'C', i("buildcraftsilicon:chipset_gold")),
         "buildcraftrobotics:robot_station", 1, null),
      shaped("buildcraftrobotics:zone_planner", "misc", null, null,
         List.of("PPP", "GdG", "III"),
         keys('P', i("minecraft:paper"), 'G', i("buildcraftcore:gear_gold"), 'd', i("buildcraftsilicon:chipset_diamond"), 'I', i("#c:ingots/iron")),
         "buildcraftrobotics:zone_planner", 1, null),
      shaped("buildcraftsilicon:advanced_crafting_table", "misc", null, null,
         List.of("OtO", "OcO", "OrO"),
         keys('O', i("minecraft:obsidian"), 't', i("minecraft:crafting_table"), 'c', i("#c:chests/wooden"), 'r', i("buildcraftsilicon:chipset_redstone")),
         "buildcraftsilicon:advanced_crafting_table", 1, null),
      shaped("buildcraftsilicon:assembly_table", "misc", null, null,
         List.of("OdO", "OrO", "OgO"),
         keys('O', i("minecraft:obsidian"), 'd', i("#c:gems/diamond"), 'r', i("#c:dusts/redstone"), 'g', i("buildcraftcore:gear_diamond")),
         "buildcraftsilicon:assembly_table", 1, null),
      shaped("buildcraftsilicon:charging_table", "misc", null, null,
         List.of("OiO", "OCO", "OgO"),
         keys('O', i("minecraft:obsidian"), 'i', i("#c:dusts/redstone"), 'C', i("buildcraftsilicon:chipset_redstone"), 'g', i("buildcraftcore:gear_gold")),
         "buildcraftsilicon:charging_table", 1, null),
      shaped("buildcraftsilicon:gate_basic", "misc", null, null,
         List.of(" m ", "mrm", " b "),
         keys('m', i("minecraft:brick"), 'r', i("minecraft:redstone"), 'b', i("minecraft:cobblestone")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:0b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"clay_brick\"]}}"),
      shaped("buildcraftsilicon:gate_iron_and", "misc", null, null,
         List.of(" m ", "mrm", " b "),
         keys('m', i("#c:ingots/iron"), 'r', i("minecraft:redstone"), 'b', i("minecraft:cobblestone")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:1b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_and_no_modifier\"]}}"),
      shaped("buildcraftsilicon:gate_iron_and_lapis", "misc", null, null,
         List.of(" m ", "mgm", " m "),
         keys('m', i("minecraft:lapis_lazuli"), 'g', cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:1b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:1b,modifier:1b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_and_lapis\"]}}"),
      shaped("buildcraftsilicon:gate_iron_and_quartz", "misc", null, null,
         List.of(" m ", "mgm", " m "),
         keys('m', i("minecraft:quartz"), 'g', cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:1b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:1b,modifier:2b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_and_quartz\"]}}"),
      shaped("buildcraftsilicon:gate_nether_brick_and", "misc", null, null,
         List.of(" m ", "mrm", " b "),
         keys('m', i("minecraft:nether_brick"), 'r', i("minecraft:redstone"), 'b', i("minecraft:cobblestone")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:2b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_and_no_modifier\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_and_diamond_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:3b,modifier:3b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:3b,modifier:3b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_or_diamond\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_and_lapis_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:3b,modifier:1b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:3b,modifier:1b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_or_lapis\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_and_no_modifier_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:3b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:3b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_or_no_modifier\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_and_quartz_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:3b,modifier:2b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:3b,modifier:2b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_or_quartz\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_or_diamond_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:3b,modifier:3b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:3b,modifier:3b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_and_diamond\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_or_lapis_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:3b,modifier:1b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:3b,modifier:1b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_and_lapis\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_or_no_modifier_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:3b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:3b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_and_no_modifier\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_gold_or_quartz_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:3b,modifier:2b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:3b,modifier:2b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"gold_and_quartz\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_and_diamond_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:1b,modifier:3b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:1b,modifier:3b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_or_diamond\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_and_lapis_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:1b,modifier:1b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:1b,modifier:1b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_or_lapis\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_and_no_modifier_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:1b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:1b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_or_no_modifier\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_and_quartz_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:1b,modifier:2b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:1b,modifier:2b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_or_quartz\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_or_diamond_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:1b,modifier:3b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:1b,modifier:3b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_and_diamond\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_or_lapis_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:1b,modifier:1b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:1b,modifier:1b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_and_lapis\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_or_no_modifier_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:1b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:1b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_and_no_modifier\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_iron_or_quartz_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:1b,modifier:2b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:1b,modifier:2b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"iron_and_quartz\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_and_diamond_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:2b,modifier:3b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:2b,modifier:3b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_or_diamond\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_and_lapis_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:2b,modifier:1b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:2b,modifier:1b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_or_lapis\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_and_no_modifier_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:2b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:2b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_or_no_modifier\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_and_quartz_to_or", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:0b,material:2b,modifier:2b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:1b,material:2b,modifier:2b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_or_quartz\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_or_diamond_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:2b,modifier:3b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:2b,modifier:3b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_and_diamond\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_or_lapis_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:2b,modifier:1b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:2b,modifier:1b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_and_lapis\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_or_no_modifier_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:2b,modifier:0b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:2b,modifier:0b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_and_no_modifier\"]}}"),
      shapeless("buildcraftsilicon:gate_swap_nether_brick_or_quartz_to_and", "misc", "buildcraft_gate_swap", null,
         List.of(cd("buildcraftsilicon:plug_gate", "{gate:{logic:1b,material:2b,modifier:2b}}")),
         "buildcraftsilicon:plug_gate", 1, "{\"minecraft:custom_data\":\"{gate:{logic:0b,material:2b,modifier:2b}}\",\"minecraft:custom_model_data\":{\"strings\":[\"nether_brick_and_quartz\"]}}"),
      shaped("buildcraftsilicon:integration_table", "misc", null, null,
         List.of("OiO", "OrO", "OgO"),
         keys('O', i("minecraft:obsidian"), 'i', i("#c:ingots/gold"), 'r', i("buildcraftsilicon:chipset_iron"), 'g', i("buildcraftcore:gear_diamond")),
         "buildcraftsilicon:integration_table", 1, null),
      shaped("buildcraftsilicon:laser", "misc", null, null,
         List.of("rro", "rdd", "rro"),
         keys('r', i("#c:dusts/redstone"), 'd', i("#c:gems/diamond"), 'o', i("minecraft:obsidian")),
         "buildcraftsilicon:laser", 1, null),
      shaped("buildcraftsilicon:packager", "misc", null, null,
         List.of(" I ", "ICI", " P "),
         keys('I', i("#c:ingots/iron"), 'C', i("minecraft:crafting_table"), 'P', i("minecraft:piston")),
         "buildcraftsilicon:packager", 1, null),
      shaped("buildcraftsilicon:programming_table", "misc", null, null,
         List.of("OCO", "ORO", "OgO"),
         keys('O', i("minecraft:obsidian"), 'R', i("buildcraftsilicon:chipset_redstone"), 'C', i("minecraft:emerald"), 'g', i("buildcraftcore:gear_diamond")),
         "buildcraftsilicon:programming_table", 1, null),
      shaped("buildcraftsilicon:stamping_table", "misc", null, null,
         List.of("OWO", "ORO", "OgO"),
         keys('O', i("minecraft:obsidian"), 'W', i("minecraft:crafting_table"), 'R', i("buildcraftsilicon:chipset_redstone"), 'g', i("buildcraftcore:gear_gold")),
         "buildcraftsilicon:stamping_table", 1, null),
      shaped("buildcrafttransport:filtered_buffer", "misc", null, null,
         List.of("wdw", "wcw", "wpw"),
         keys('w', i("#minecraft:planks"), 'd', i("buildcrafttransport:pipe_diamond_item"), 'c', i("#c:chests/wooden"), 'p', i("minecraft:piston")),
         "buildcrafttransport:filtered_buffer", 1, null),
      shapeless("buildcrafttransport:pipe_clay_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_clay_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_clay_fluid", 1, null),
      shaped("buildcrafttransport:pipe_clay_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("minecraft:clay"), 'g', i("#c:glass_blocks/colorless"), 'r', i("minecraft:clay")),
         "buildcrafttransport:pipe_clay_item", 8, null),
      shapeless("buildcrafttransport:pipe_cobble_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_cobble_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_cobble_fluid", 1, null),
      shaped("buildcrafttransport:pipe_cobble_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#c:cobblestones/normal"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:cobblestones/normal")),
         "buildcrafttransport:pipe_cobble_item", 8, null),
      shapeless("buildcrafttransport:pipe_cobble_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_cobble_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_cobble_power", 1, null),
      shapeless("buildcrafttransport:pipe_cobble_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_cobble_rf")),
         "buildcrafttransport:pipe_cobble_power", 1, null),
      shapeless("buildcrafttransport:pipe_cobble_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_cobble_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_cobble_rf", 1, null),
      shaped("buildcrafttransport:pipe_daizuli_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("minecraft:lapis_block"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:gems/diamond")),
         "buildcrafttransport:pipe_daizuli_item", 8, null),
      shapeless("buildcrafttransport:pipe_diamond_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_diamond_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_diamond_fluid", 1, null),
      shaped("buildcrafttransport:pipe_diamond_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#c:gems/diamond"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:gems/diamond")),
         "buildcrafttransport:pipe_diamond_item", 8, null),
      shapeless("buildcrafttransport:pipe_diamond_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_diamond_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_diamond_power", 1, null),
      shapeless("buildcrafttransport:pipe_diamond_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_diamond_rf")),
         "buildcrafttransport:pipe_diamond_power", 1, null),
      shapeless("buildcrafttransport:pipe_diamond_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_diamond_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_diamond_rf", 1, null),
      shapeless("buildcrafttransport:pipe_diamond_wood_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_diamond_wood_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_diamond_wood_fluid", 1, null),
      shaped("buildcrafttransport:pipe_diamond_wood_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#minecraft:planks"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:gems/diamond")),
         "buildcrafttransport:pipe_diamond_wood_item", 8, null),
      shapeless("buildcrafttransport:pipe_diamond_wood_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_diamond_wood_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_diamond_wood_power", 1, null),
      shapeless("buildcrafttransport:pipe_diamond_wood_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_diamond_wood_rf")),
         "buildcrafttransport:pipe_diamond_wood_power", 1, null),
      shapeless("buildcrafttransport:pipe_diamond_wood_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_diamond_wood_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_diamond_wood_rf", 1, null),
      shapeless("buildcrafttransport:pipe_emzuli_item", "misc", "buildcraft_pipes", null,
         List.of(i("buildcrafttransport:pipe_diamond_wood_item"), i("minecraft:lapis_block")),
         "buildcrafttransport:pipe_emzuli_item", 1, null),
      shapeless("buildcrafttransport:pipe_gold_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_gold_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_gold_fluid", 1, null),
      shaped("buildcrafttransport:pipe_gold_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#c:ingots/gold"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:ingots/gold")),
         "buildcrafttransport:pipe_gold_item", 8, null),
      shapeless("buildcrafttransport:pipe_gold_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_gold_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_gold_power", 1, null),
      shapeless("buildcrafttransport:pipe_gold_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_gold_rf")),
         "buildcrafttransport:pipe_gold_power", 1, null),
      shapeless("buildcrafttransport:pipe_gold_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_gold_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_gold_rf", 1, null),
      shapeless("buildcrafttransport:pipe_iron_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_iron_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_iron_fluid", 1, null),
      shaped("buildcrafttransport:pipe_iron_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#c:ingots/iron"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:ingots/iron")),
         "buildcrafttransport:pipe_iron_item", 8, null),
      shapeless("buildcrafttransport:pipe_iron_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_iron_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_iron_power", 1, null),
      shapeless("buildcrafttransport:pipe_iron_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_iron_rf")),
         "buildcrafttransport:pipe_iron_power", 1, null),
      shapeless("buildcrafttransport:pipe_iron_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_iron_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_iron_rf", 1, null),
      shaped("buildcrafttransport:pipe_lapis_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("minecraft:lapis_block"), 'g', i("#c:glass_blocks/colorless"), 'r', i("minecraft:lapis_block")),
         "buildcrafttransport:pipe_lapis_item", 8, null),
      shaped("buildcrafttransport:pipe_obsidian_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("minecraft:obsidian"), 'g', i("#c:glass_blocks/colorless"), 'r', i("minecraft:obsidian")),
         "buildcrafttransport:pipe_obsidian_item", 8, null),
      shapeless("buildcrafttransport:pipe_quartz_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_quartz_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_quartz_fluid", 1, null),
      shaped("buildcrafttransport:pipe_quartz_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("minecraft:quartz_block"), 'g', i("#c:glass_blocks/colorless"), 'r', i("minecraft:quartz_block")),
         "buildcrafttransport:pipe_quartz_item", 8, null),
      shapeless("buildcrafttransport:pipe_quartz_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_quartz_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_quartz_power", 1, null),
      shapeless("buildcrafttransport:pipe_quartz_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_quartz_rf")),
         "buildcrafttransport:pipe_quartz_power", 1, null),
      shapeless("buildcrafttransport:pipe_quartz_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_quartz_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_quartz_rf", 1, null),
      shapeless("buildcrafttransport:pipe_sandstone_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_sandstone_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_sandstone_fluid", 1, null),
      shaped("buildcrafttransport:pipe_sandstone_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#c:sandstone/blocks"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:sandstone/blocks")),
         "buildcrafttransport:pipe_sandstone_item", 8, null),
      shapeless("buildcrafttransport:pipe_sandstone_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_sandstone_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_sandstone_power", 1, null),
      shapeless("buildcrafttransport:pipe_sandstone_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_sandstone_rf")),
         "buildcrafttransport:pipe_sandstone_power", 1, null),
      shapeless("buildcrafttransport:pipe_sandstone_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_sandstone_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_sandstone_rf", 1, null),
      shapeless("buildcrafttransport:pipe_sealant", "misc", null, null,
         List.of(i("minecraft:slime_ball")),
         "buildcrafttransport:waterproof", 1, null),
      shapeless("buildcrafttransport:pipe_sealant_from_green_dye", "misc", null, null,
         List.of(i("minecraft:green_dye")),
         "buildcrafttransport:waterproof", 1, null),
      shapeless("buildcrafttransport:pipe_stone_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_stone_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_stone_fluid", 1, null),
      shaped("buildcrafttransport:pipe_stone_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#c:stones"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:stones")),
         "buildcrafttransport:pipe_stone_item", 8, null),
      shapeless("buildcrafttransport:pipe_stone_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_stone_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_stone_power", 1, null),
      shapeless("buildcrafttransport:pipe_stone_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_stone_rf")),
         "buildcrafttransport:pipe_stone_power", 1, null),
      shapeless("buildcrafttransport:pipe_stone_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_stone_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_stone_rf", 1, null),
      shaped("buildcrafttransport:pipe_stripes_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("buildcraftcore:gear_gold"), 'g', i("#c:glass_blocks/colorless"), 'r', i("buildcraftcore:gear_gold")),
         "buildcrafttransport:pipe_stripes_item", 8, null),
      shaped("buildcrafttransport:pipe_structure", "misc", null, null,
         List.of("cgc"),
         keys('c', i("#c:cobblestones/normal"), 'g', i("minecraft:gravel")),
         "buildcrafttransport:pipe_structure", 8, null),
      shapeless("buildcrafttransport:pipe_void_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_void_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_void_fluid", 1, null),
      shaped("buildcrafttransport:pipe_void_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#c:dyes/black"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_void_item", 8, null),
      shapeless("buildcrafttransport:pipe_wood_fluid", "misc", "buildcraft_fluid_pipes", null,
         List.of(i("buildcrafttransport:pipe_wood_item"), i("buildcrafttransport:waterproof")),
         "buildcrafttransport:pipe_wood_fluid", 1, null),
      shaped("buildcrafttransport:pipe_wood_item", "misc", "buildcraft_pipes", null,
         List.of("lgr"),
         keys('l', i("#minecraft:planks"), 'g', i("#c:glass_blocks/colorless"), 'r', i("#minecraft:planks")),
         "buildcrafttransport:pipe_wood_item", 8, null),
      shapeless("buildcrafttransport:pipe_wood_power", "misc", "buildcraft_power_pipes", null,
         List.of(i("buildcrafttransport:pipe_wood_item"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_wood_power", 1, null),
      shapeless("buildcrafttransport:pipe_wood_power_from_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_wood_rf")),
         "buildcrafttransport:pipe_wood_power", 1, null),
      shapeless("buildcrafttransport:pipe_wood_rf", "misc", null, "[{\"condition\":\"fabric:all_mods_loaded\",\"values\":[\"team_reborn_energy\"]}]",
         List.of(i("buildcrafttransport:pipe_wood_power"), i("#c:dusts/redstone")),
         "buildcrafttransport:pipe_wood_rf", 1, null),
      shaped("buildcrafttransport:plug_blocker", "misc", null, null,
         List.of("s"),
         keys('s', i("buildcrafttransport:pipe_structure")),
         "buildcrafttransport:plug_blocker", 4, null),
      shaped("buildcrafttransport:plug_power_adaptor", "misc", null, null,
         List.of("sis", "sgs", "srs"),
         keys('s', i("buildcrafttransport:pipe_structure"), 'g', i("buildcraftcore:gear_stone"), 'r', i("minecraft:redstone"), 'i', i("#c:ingots/gold")),
         "buildcrafttransport:plug_power_adaptor", 4, null),
      shapeless("buildcrafttransport:residue_to_pipe_sealant", "misc", null, null,
         List.of(i("buildcraftenergy:oil_residue_bucket")),
         "buildcrafttransport:waterproof", 8, null)
   );

   private BCRecipeDefs() {
   }
}
